services:
  catalogdb:
    image: postgres

  catalog.api:
    image: ${DOCKER_REGISTRY}catalogapi
    build:
      context: ./src
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

volumes:
  postgres_catalog: